plugins:
    - prettier-plugin-java
    - prettier-plugin-svelte

overrides:
    - files:
          - "*"
      options:
          printWidth: 140
          tabWidth: 4
          useTabs: false
          trailingComma: "none"
